package prompt:gen;

interface chat {
	record sys {
		model: string,
		system: string,
		user: string,
	}

	record msg {
		assistant: string,
		tool: option<string>,
		tool-call-id: option<string>,
		user: option<string>,
	}
}

world wasm-prompter {
	use chat.{sys, msg};

	export init: func() -> sys;
	export build: func(response: string) -> msg;
}
