package openai:chat;

interface chat {
	resource chat-completion {
		constructor(model: string, system: string, user: string);
		generate: func(assistant: string, tool: option<string>, tool-call-id: option<string>, user: option<string>);
	}
}

world import-chat {
	import chat;
	export init: func();
	export build: func(response: string);
}
