package promptrs:gen;

interface chat {
	use wasi:filesystem/types@0.2.5.{error-code};

	record sys {
		base-url: string,
		model: string,
		system: string,
		user: string,
	}

	record msg {
		assistant: tuple<string, string, list<string>, string>,
		tool: tuple<string, list<string>, string>,
		tool-call-id: option<string>,
		status: option<tuple<string, string>>,
		user: option<string>,
	}

	resource generator {
		constructor(offset: option<s32>);
		init: func() -> result<sys, error-code>;
		build: func(response: string) -> result<msg, error-code>;
	}
}

world ifc {
	import wasi:clocks/monotonic-clock@0.2.5;
	import wasi:filesystem/preopens@0.2.5;
	export chat;
}
