package promptrs:gen;

interface chat {
	record sys {
		base-url: string,
		model: string,
		system: string,
		user: string,
	}

	record msg {
		assistant: string,
		tool: option<string>,
		tool-call-id: option<string>,
		user: option<string>,
	}

	resource generator {
		constructor();
		init: func() -> sys;
		build: func(response: string) -> msg;
	}
}

world ifc {
	import wasi:clocks/monotonic-clock@0.2.5;
	import wasi:filesystem/preopens@0.2.5;
	export chat;
}
