package promptrs:gen;

interface chat {
	record sys {
		base-url: string,
		model: string,
		system: string,
		user: string,
	}

	record msg {
		assistant: tuple<string, string, list<string>, string>,
		tool: tuple<string, list<string>, string>,
		tool-call-id: option<string>,
		status: option<tuple<string, string>>,
		user: option<string>,
	}

	resource generator {
		constructor();
		init: func() -> sys;
		build: func(response: string) -> msg;
	}
}

world ifc {
	export chat;
}
