package prompt:gen;

interface chat {
	record sys {
		base-url: string,
		model: string,
		system: string,
		user: string,
	}

	record msg {
		assistant: string,
		tool: option<string>,
		tool-call-id: option<string>,
		user: option<string>,
	}
}

world wasm-prompter {
	use chat.{sys, msg};

	import wasi:clocks/monotonic-clock@0.2.5;
	import wasi:filesystem/preopens@0.2.5;
	export init: func() -> sys;
	export build: func(response: string) -> msg;
}
